version: "3"

services:

    database:
        container_name: PSQL_DATABASE
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - database_data:/var/lib/postgresql
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=flash
            - POSTGRES_PASSWORD=dydka
            - POSTGRES_DB=database
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
          - project_network

    pgadmin:
        container_name: PSQL_PGADMIN
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - "5050:80"
        volumes:
          - pgadmin_data:/var/lib/pgadmin
        networks:
            - project_network

# connect : psql postgresql://flash:dydka@localhost:5432/database

networks:
    project_network:

volumes:
  pgadmin_data:
      driver: local
  database_data:
    driver: local