version: "3"

services:

    database:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
          - database_data:/var/lib/postgresql
      ports:
          - "5432:5432"
      environment:
          - POSTGRES_USER=flash
          - POSTGRES_PASSWORD=dydka
          - POSTGRES_DB=database
          - ALLOW_EMPTY_PASSWORD=yes

    pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
      volumes:
        - pgadmin_data:/var/lib/pgadmin

# connect : psql postgresql://flash:dydka@localhost:5432/database

volumes:
  pgadmin_data:
      driver: local
  database_data:
    driver: local