version: "3"

services:

    database:
        
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - database_data:/var/lib/postgresql
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=flash
            - POSTGRES_PASSWORD=dydka
            - POSTGRES_DB=database
            - ALLOW_EMPTY_PASSWORD=yes

# connect : psql postgresql://flash:dydka@localhost:5432/database

volumes:
  database_data:
    driver: local